name: jittor
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==0.27.2
    - astunparse==1.6.3
    - attrs==24.2.0
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - cupy-cuda12x==13.2.0
    - diffusers==0.26.0.dev0
    - fastrlock==0.8.2
    - filelock==3.15.4
    - fsspec==2024.6.1
    - huggingface-hub==0.24.3
    - idna==3.7
    - imagehash==4.3.1
    - importlib-metadata==8.2.0
    - jdiffusion==1.0
    - jittor==1.3.9.10
    - jsonlines==4.0.0
    - jtorch==0.1.8
    - numpy==1.24.4
    - packaging==24.1
    - peft==0.10.0
    - pillow==10.4.0
    - psutil==6.0.0
    - pywavelets==1.6.0
    - pyyaml==6.0.2
    - regex==2024.7.24
    - requests==2.32.3
    - safetensors==0.4.4
    - scipy==1.13.1
    - setuptools==72.2.0
    - six==1.16.0
    - tokenizers==0.13.3
    - torch==2.0.0
    - tqdm==4.66.5
    - transformers==4.26.1
    - typing-extensions==4.12.2
    - urllib3==2.2.2
    - zipp==3.20.0
prefix: /mnt/vepfs/chenyixiao/miniconda3/envs/jittor

